const money = (n = 0) => `₹ ${Number(n || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`;
const d = (v) => v ? new Date(v).toLocaleDateString('en-IN') : new Date().toLocaleDateString('en-IN');
const esc = (s = '') => String(s ?? '').replace(/[&<>"]/g, m => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[m]));
const companyDefaults = { name:'KRISHNARPAN ASSOCIATE', legal:'Krushnarpan Chits Pvt.Ltd', address:'SQUARE LINK MARKET NEAR GOVERNMENT POLYTECHNIC COLLEGE GADGE NAGAR, AMRAVATI', phone:'7038927448', email:'bhushanjawarkar007@gmail.com', state:'27-Maharashtra', cin:'U64990MH2025PTC451412', logoUrl:'/logo.png', stampUrl:'/stamp.png' };
const cobj=(c={})=>({...companyDefaults,...c});
const companyBlock = (c = {}, right=false) => { c=cobj(c); return `<div class="company ${right?'rightHead':''}"><div class="logoBox"><img src="${c.logoUrl}" onerror="this.style.display='none'"/></div><div class="companyText"><h2>${esc(c.name)}</h2><p>${esc(c.address)}</p><p>Phone no.: ${esc(c.phone)} Email: ${esc(c.email)}</p><p>State: ${esc(c.state)}</p></div></div>` };
function openPrint(html) { const w = window.open('', '_blank'); w.document.write(`<!doctype html><html><head><title>BC Report</title><style>@page{size:A4;margin:12mm}body{font-family:Arial,Helvetica,sans-serif;color:#000;font-size:11px}.company{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;min-height:85px}.rightHead{flex-direction:row}.companyText{text-align:right;flex:1}.company h2{font-size:15px;margin:0 0 4px}.company p{margin:2px 0}.logoBox{width:170px}.logoBox img{max-width:160px;max-height:75px}.greenLine{border-top:2px solid #009c3b;margin:35px 0 18px}.title{text-align:center;color:#009c3b;font-size:16px;font-weight:700;margin:0 0 24px}.under{text-decoration:underline;text-align:center;font-size:17px;font-weight:700;margin:18px 0}table{width:100%;border-collapse:collapse}th{background:#dfe3e8;font-weight:700}td,th{border:1px solid #c9c9c9;padding:6px;text-align:left;vertical-align:top}.noBorder td{border:none;padding:4px}.right{text-align:right}.center{text-align:center}.green{color:#009c3b}.red{color:#c00}.row2{display:flex;justify-content:space-between}.mt{margin-top:18px}.sign{text-align:right;margin-top:30px}.stampImg{width:110px;height:110px;object-fit:contain}.small{font-size:10px}.desc{font-size:10px;font-weight:700;line-height:1.5}.balance{font-weight:700;text-align:right;margin-top:16px}.receiptDescription{white-space:pre-wrap;margin:8px 0 12px;line-height:1.45}.partyName{font-size:15px;font-weight:700;margin:18px 0}.pageBreak{page-break-before:always}.chartTitle{text-align:center;font-size:18px;font-weight:700;margin:25px 0}.gold th{background:#bc8f00;color:#111}.gold td{background:#ffe8a3;text-align:center}.narrow td,.narrow th{padding:4px;font-size:10px}</style></head><body>${html}</body></html>`); w.document.close(); w.focus(); setTimeout(() => w.print(), 500); }
export function printReceipt({ company = {}, tx = {}, member = {}, group = {} }) {
  const c=cobj(company); const payerName = tx.payerName || member.primaryName || ''; const payerPhone = tx.payerPhone || member.phone || '';
  const description = tx.notes && String(tx.notes).trim() ? `<div class="receiptDescription">${esc(tx.notes)}</div>` : `<div class="receiptDescription">GROUP NO - ${esc(group.name || '')}\nINST NO - ${esc(tx.cycleMonth || '')}</div>`;
  openPrint(`<div class="company"><div><h2>${esc(c.name)}</h2><p>${esc(c.address)}</p><p>Phone : ${esc(c.phone)}</p><p>Email : ${esc(c.email)}</p><p>State: ${esc(c.state)}</p></div><div class="logoBox right"><img src="${c.logoUrl}" onerror="this.style.display='none'"/></div></div><div class="greenLine"></div><div class="title">Payment Receipt</div><div class="row2"><div><b>Received From</b><br/>${esc(payerName)}<br/>Contact No: ${esc(payerPhone)}</div><div><b>Receipt Details</b><br/>Receipt No: ${esc(tx.receiptNo || tx._id || '')}<br/>Date: ${d(tx.paidDate)}</div></div><table class="noBorder mt"><tr><td><b>Description</b><br/>${description}</td><td class="right">${money(tx.amount)}</td></tr><tr><td>( PAYMENT BY ${esc(tx.method || 'Cash')} )</td><td class="right">For: ${esc(c.name)}</td></tr></table><div class="sign"><b>Authorized Signatory</b><br/><br/><img class="stampImg" src="${c.stampUrl}" onerror="this.outerHTML='STAMP'"/></div>`);
}
export function printLedger({ company = {}, group = {}, members = [] }) {
  const rows = members.map(m => `<tr><td>${esc(group.name || '')}</td><td>${esc(m.ticketNumber || '')}</td><td>${esc(m.primaryName || '')}${(m.jointMembers || []).filter(j => !j.isDeleted).length ? '<br/><span class="small">Joint: ' + (m.jointMembers || []).filter(j => !j.isDeleted).map(j => `${esc(j.name)} (${money(j.shareAmount)})`).join(', ') + '</span>' : ''}</td><td>${esc(m.phone || '')}</td><td>${d(m.joinedAt)}</td><td class="red">${money(0)}</td><td class="green">${money(m.ticketAmount)}</td><td>${money(-m.ticketAmount)}</td><td>${esc(m.agentName || '-')}</td></tr>`).join('');
  openPrint(`<h2 class="center" style="margin:0">BC GROUP LEDGER</h2><p class="center" style="margin:2px 0 14px">Auction List Report</p><table><thead><tr><th>Group</th><th>Ticket</th><th>Name</th><th>Mobile</th><th>App. Date</th><th>Due</th><th>Paid</th><th>Remaining</th><th>Agent</th></tr></thead><tbody>${rows}</tbody></table><div class="balance">Total Rows: ${members.length}</div>`);
}
export function printStatement({ company = {}, member = {}, transactions = [] }) {
  let payable = 0, receivable = 0;
  const rows = transactions.map((t,i) => { const amt=Number(t.amount||0); const isIn=['member_payment','income','commission','penalty','receivable'].includes(t.type); if(isIn) payable += amt; else receivable += amt; const bal=payable-receivable; return `<tr><td>${d(t.paidDate)}</td><td>${esc(t.type || 'Payment-In')}</td><td>${esc(t.receiptNo || i+1)}</td><td>${esc(t.status || 'Unused')}</td><td>${money(amt)}</td><td>${isIn?money(amt):'-'}</td><td>${money(bal)}</td><td>${isIn?money(payable):'-'}</td><td>${!isIn?money(receivable):money(payable)}</td></tr><tr><td colspan="9" class="desc">Description: ${esc(t.notes || `GROUP NO. ${member.group?.name || ''} CHIT VALUE : ${money(member.ticketAmount)} INST. NO. ${t.cycleMonth || ''} ( BEING PAYMENT PAID BY ${String(t.method||'cash').toUpperCase()} )`)}<br/>Payment Type: ${esc(t.method || 'Cash')}</td></tr>`; }).join('');
  const c=cobj(company);
  openPrint(`${companyBlock(c,true)}<hr class="mt"/><div class="under">Party statement</div><div class="partyName">Party name: ${esc(member.primaryName || '')} ( ${esc(member.group?.name || '')} )</div><p><b>Contact No:</b> ${esc(member.phone || '')} &nbsp; <b>Agent:</b> ${esc(member.agentName || '-')}</p><table class="narrow"><thead><tr><th>Date</th><th>Txn Type</th><th>Ref No.</th><th>Payment Status</th><th>Total</th><th>Received / Paid</th><th>Txn Balance</th><th>Receivable Balance</th><th>Payable Balance</th></tr></thead><tbody>${rows}</tbody></table>`);
}
export function printBCChart({ company = {}, plans = [] }) {
  const defaults=[['1st month','22000','54000','104000','208000'],['2nd month','20000','50000','100000','200000'],['3rd to 9th month','15400','38500','77000','154000'],['10th to 16th month','15400 To 17000','38500 To 41000','77000 To 85800','154000 To 171000'],['17th to 21th month','17000 To 19000','41000 To 44800','85800 To 91100','171000 To 185000'],['21th to 25 month','19000 To 20000','44800 To 50000','91100 To 100000','185000 To 200000']];
  const rows=(plans.length?plans:defaults).map(r=>Array.isArray(r)?r:[`${r.monthFrom}-${r.monthTo}`, r.amount, '', '', '']).map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('');
  const c=cobj(company);
  openPrint(`<div class="center"><img src="${c.logoUrl}" style="max-width:420px;max-height:140px"/></div><hr class="mt"/><p class="right">CIN-${esc(c.cin)}<br/>${esc(c.legal)}</p><div class="chartTitle">मासिक हप्ता भरना रकम पत्रक</div><table class="gold"><thead><tr><th>MONTHS</th><th>5 LAKH</th><th>12.5 LAKH</th><th>25 LAKH</th><th>50 LAKH</th></tr></thead><tbody>${rows}</tbody></table><h3>➤ सदर हप्त्यात रकम थोडीफार कमी जास्त होईल.</h3><h3>➤ दिनांक २५ पर्यंत भरणे आवश्यक आहे.</h3>`);
}
